[package]
name = "windows_dll"
version = "0.1.0"
authors = ["Kai <thiskaiguy@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies.syn]
version = "0.15.26"
features = [
    "full",
    "extra-traits",
]
