[workspace]
members = [
    ".",
    "codegen",
]

[package]
name = "windows_dll"
version = "0.1.0"
authors = ["Kai <thiskaiguy@gmail.com>"]
edition = "2018"

[dependencies]
windows-dll-codegen = { path = "codegen" }

[dependencies.winapi]
version = "0.3.7"
features = [
    "ntdef",
    "minwindef",
    "winerror",
    "libloaderapi",
    "winuser",
]
