[package]
name = "windows-dll-codegen"
version = "0.1.0"
authors = ["Kai <thiskaiguy@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
proc-macro-crate = "0.1"

[dependencies.syn]
version = "1.0"
features = [
    "full",
    "extra-traits",
]
